# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Property_Profile.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QWidget, QApplication


class Ui_Form(QWidget):

    def __init__(self):
        super().__init__()
        self.setupUi()



    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1122, 847)
        self.label_13 = QtWidgets.QLabel(self)
        self.label_13.setGeometry(QtCore.QRect(720, 60, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(190, 60, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(0, 30, 1121, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(990, 0, 121, 28))
        self.pushButton.setObjectName("pushButton")
        self.house_info = QtWidgets.QTableWidget(self)
        self.house_info.setGeometry(QtCore.QRect(40, 80, 491, 441))
        self.house_info.setObjectName("house_info")
        self.house_info.setColumnCount(1)
        self.house_info.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.house_info.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        # brush.setStyle(QtCore.Qt.NoBrush)
        # item.setForeground(brush)
        # self.house_info.setItem(0, 0, item)
        self.house_info.horizontalHeader().setDefaultSectionSize(300)
        self.owner_info = QtWidgets.QTableWidget(self)
        self.owner_info.setGeometry(QtCore.QRect(560, 80, 521, 441))
        self.owner_info.setObjectName("owner_info")
        self.owner_info.setColumnCount(1)
        self.owner_info.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.owner_info.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem("Test")
        # brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        # brush.setStyle(QtCore.Qt.HorPattern)
        # item.setForeground(brush)
        # self.owner_info.setItem(0, 0, item)
        self.owner_info.horizontalHeader().setDefaultSectionSize(300)
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(40, 540, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.AdditionalInfo_txt = QtWidgets.QPlainTextEdit(self)
        self.AdditionalInfo_txt.setGeometry(QtCore.QRect(40, 570, 431, 261))
        self.AdditionalInfo_txt.setObjectName("AdditionalInfo_txt")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(490, 540, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Button_NOresponse = QtWidgets.QRadioButton(self)
        self.Button_NOresponse.setGeometry(QtCore.QRect(740, 590, 131, 20))
        self.Button_NOresponse.setObjectName("Button_NOresponse")
        self.Respond_person = QtWidgets.QRadioButton(self)
        self.Respond_person.setGeometry(QtCore.QRect(890, 590, 141, 20))
        self.Respond_person.setObjectName("Respond_person")
        self.Button_responded = QtWidgets.QRadioButton(self)
        self.Button_responded.setGeometry(QtCore.QRect(630, 590, 95, 20))
        self.Button_responded.setObjectName("Button_responded")
        self.Very_interested = QtWidgets.QRadioButton(self)
        self.Very_interested.setGeometry(QtCore.QRect(630, 640, 111, 20))
        self.Very_interested.setObjectName("Very_interested")
        self.Interested = QtWidgets.QRadioButton(self)
        self.Interested.setGeometry(QtCore.QRect(770, 640, 95, 20))
        self.Interested.setObjectName("Interested")
        self.Not_interested = QtWidgets.QRadioButton(self)
        self.Not_interested.setGeometry(QtCore.QRect(890, 640, 111, 20))
        self.Not_interested.setObjectName("Not_interested")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(550, 590, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(530, 640, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 0, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_3.setGeometry(QtCore.QRect(770, 0, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Owner Information:"))
        self.label_7.setText(_translate("Form", "House Information:"))
        self.label_11.setText(_translate("Form", "Property Information"))
        self.pushButton.setText(_translate("Form", "Edit Information"))
        item = self.house_info.verticalHeaderItem(0)
        item.setText(_translate("Form", "Adress:"))
        item = self.house_info.verticalHeaderItem(1)
        item.setText(_translate("Form", "City:"))
        item = self.house_info.verticalHeaderItem(2)
        item.setText(_translate("Form", "Zip Code:"))
        item = self.house_info.verticalHeaderItem(3)
        item.setText(_translate("Form", "State:"))
        item = self.house_info.verticalHeaderItem(4)
        item.setText(_translate("Form", "Property Type:"))
        item = self.house_info.verticalHeaderItem(5)
        item.setText(_translate("Form", "Building Size:"))
        item = self.house_info.verticalHeaderItem(6)
        item.setText(_translate("Form", "Lot Size(SqFt):"))
        item = self.house_info.verticalHeaderItem(7)
        item.setText(_translate("Form", "Baths:"))
        item = self.house_info.verticalHeaderItem(8)
        item.setText(_translate("Form", "Bedrooms:"))
        item = self.house_info.verticalHeaderItem(9)
        item.setText(_translate("Form", "APN:"))
        item = self.house_info.verticalHeaderItem(10)
        item.setText(_translate("Form", "Year Built:"))
        item = self.house_info.verticalHeaderItem(11)
        item.setText(_translate("Form", "Number of Units:"))
        item = self.house_info.verticalHeaderItem(12)
        item.setText(_translate("Form", "Primary Garage Type:"))
        item = self.house_info.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Information", "Hello"))
        item = self.owner_info.verticalHeaderItem(0)
        item.setText(_translate("Form", "First Name:"))
        item = self.owner_info.verticalHeaderItem(1)
        item.setText(_translate("Form", "Last Name:"))
        item = self.owner_info.verticalHeaderItem(2)
        item.setText(_translate("Form", "Mailing Adress:"))
        item = self.owner_info.verticalHeaderItem(3)
        item.setText(_translate("Form", "Mailing City:"))
        item = self.owner_info.verticalHeaderItem(4)
        item.setText(_translate("Form", "Mailing Zip Code:"))
        item = self.owner_info.verticalHeaderItem(5)
        item.setText(_translate("Form", "Mailing State:"))
        item = self.owner_info.verticalHeaderItem(6)
        item.setText(_translate("Form", "Loan to Value Ratio:"))
        item = self.owner_info.verticalHeaderItem(7)
        item.setText(_translate("Form", "Total Outstanding Loans:"))
        item = self.owner_info.verticalHeaderItem(8)
        item.setText(_translate("Form", "Amount of Delinquent Taxes:"))
        item = self.owner_info.verticalHeaderItem(9)
        item.setText(_translate("Form", "Owner Occuppied:"))
        item = self.owner_info.verticalHeaderItem(10)
        item.setText(_translate("Form", "Purchased Prise:"))
        item = self.owner_info.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Information"))
        __sortingEnabled = self.owner_info.isSortingEnabled()
        self.owner_info.setSortingEnabled(False)
        self.owner_info.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("Form", "Additional Comments:"))
        self.label_9.setText(_translate("Form", "Status:"))
        self.Button_NOresponse.setText(_translate("Form", "Hasn\'t Responded "))
        self.Respond_person.setText(_translate("Form", "Respomd Personally"))
        self.Button_responded.setText(_translate("Form", "Responded"))
        self.Very_interested.setText(_translate("Form", "Very Interested"))
        self.Interested.setText(_translate("Form", "Interested "))
        self.Not_interested.setText(_translate("Form", "Not Interested"))
        self.label.setText(_translate("Form", "Status: "))
        self.label_2.setText(_translate("Form", "Interested:"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))

    def update_text_boxes(self,column_headers,row_data):
        for i in range(self.house_info.rowCount()):
            item = self.house_info.verticalHeaderItem(i)
            for q in range(len(column_headers)):
                if item.text().upper()[:-1] == column_headers[q].upper():
                    print('Equal')
                    info_cell =  QtWidgets.QTableWidgetItem(row_data[q])
                    info_cell.setFlags(QtCore.Qt.ItemIsEnabled)
                    self.house_info.setItem(0,i,info_cell)

        for i in range(self.owner_info.rowCount()):
            item = self.owner_info.verticalHeaderItem(i)
            for q in range(len(column_headers)):
                if item.text().upper()[:-1] == column_headers[q].upper():
                    print('Equal')
                    info_cell = QtWidgets.QTableWidgetItem(row_data[q])
                    info_cell.setFlags(QtCore.Qt.ItemIsEnabled)
                    self.owner_info.setItem(0,i, info_cell)

if __name__ == '__main__':                      #
    import sys
    app = QApplication(sys.argv)
    window = Ui_Form()

    column_test_data = ['Address','City','Baths','First Name','Last Name','Bedrooms']
    row_test_data =    ['123 Street','Townville','3','Steve','Smith','16']

    window.update_text_boxes(column_test_data,row_test_data)
    window.show()
    sys.exit(app.exec_())
